import type { Metadata } from "next";
import { Poppins, Fascinate_Inline } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], 
});

const fascinateInline = Fascinate_Inline({
  variable: "--font-fascinateinline", // Ensure consistency in variable name
  subsets: ["latin"],
  weight: "400", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${fascinateInline.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
